<?php
namespace frontend\themes\jiebao\widgets\category;
use common\models\Category;

/**
 * Created by PhpStorm.
 * User: jemi
 * Date: 2018/10/7
 * Time: 16:21
 */

class CategoryMenu extends \yii\base\Widget
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $data = Category::getCategories();
        return $this->render('index', [
            'data' => $data,
        ]);
    }

}